### ISSUE TITLE
Allow changing the port of server

### ISSUE THREAD

**Issue by Makefile-dot-in** [AndrewVos/vbar#10]
So if the user wants to run 2 instances of vbar at once or has another thing running on the same port, they can do it. The traditional way would be to add a flag for that, so you could run it on port 123 by using:

    vbar -p 123

And then add a block by using 

     vbar -p 123 add-block --name test 

I also suggest that, for the sake of ease of use, it should also be able to take it from an environment variable.

**Comment by AndrewVos** [comment]
Great idea thanks! It's in master now :)
