### ISSUE TITLE
Aur package build failed

### ISSUE THREAD

**Issue by Notevill** [AndrewVos/vbar#18]
```
# github.com/AndrewVos/vbar
go/src/github.com/AndrewVos/vbar/gtk.go:72:14: assignment mismatch: 2 variables but window.GetScreen returns 1 values
go/src/github.com/AndrewVos/vbar/gtk.go:132:14: assignment mismatch: 2 variables but window.GetScreen returns 1 values
go/src/github.com/AndrewVos/vbar/window.go:112:15: assignment mismatch: 2 variables but window.gtkWindow.GetScreen returns 1 values
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by AndrewVos** [comment]
Hi @Notevill, I'm sorry but I haven't used arch for quite a while so I'm not really supporting this project at the moment. It does look like the code is out of date with the gtk library. Feel free to fix it and submit a pull request.

**Comment by Notevill** [comment]
is this project abandoned?

**Comment by AndrewVos** [comment]
For now yes. If you can get it running I think you'll like it though :)

**Comment by AndrewVos** [comment]
@Notevill this has been fixed by the amazing @Makefile-dot-in
