### ISSUE TITLE
Allow configuring vbar with commands

### ISSUE THREAD

**Issue by AndrewVos** [AndrewVos/vbar#4]
So you could use bash to create configs?

Some examples:

```bash
vbar --add --left --name "title" --text "Title" --command "get-window-title"

vbar --remove "title"

vbar --update "title"

vbar --replace --left --name "title" --text "Title" --command "get-window-title"

vbar --css --class-name "panel" --css "background-color: red"
vbar --css --class-name "title" --css "background-color: red"

```

**Comment by AndrewVos** [comment]
@Makefile-dot-in got any thoughts on this?

**Comment by Makefile-dot-in** [comment]
@AndrewVos I'd like it, will try to implement later.

**Comment by AndrewVos** [comment]
@Makefile-dot-in already on it! It mostly works. Problem is it's a bit slow with dbus

**Comment by AndrewVos** [comment]
Definitely a lot more programmable than JSON though.

**Comment by AndrewVos** [comment]
Ok I've got some changes up https://github.com/AndrewVos/vbar/pull/5

Have a look at `file.sh` which is what config would become.

**Comment by AndrewVos** [comment]
Cool, all pretty much done I think. https://github.com/AndrewVos/vbar/tree/cli-based-config
