### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Makefile-dot-in** [AndrewVos/vbar#8]
As it stands right now, vbar doesn't have a license. By default (at least in Latvia and the U.S.) a work is still copyrighted even if it's not explicitly mentioned.

**Comment by Makefile-dot-in** [comment]
@AndrewVos Any thoughts?

**Comment by AndrewVos** [comment]
Yeah defo. Not sure which license though

**Comment by Makefile-dot-in** [comment]
I personally would vote for MIT, since a closed-source X11 bar would blalantly fail, hence no need for GPL.

**Comment by AndrewVos** [comment]
I think you're right.

**Comment by Makefile-dot-in** [comment]
@AndrewVos Could you add it then?

**Comment by AndrewVos** [comment]
Sure, done. There's a PR open, and also I made you a collaborator on this project, if you would like that.

**Comment by Makefile-dot-in** [comment]
@AndrewVos Yes, I would.

**Comment by Makefile-dot-in** [comment]
Oh wait, had to accept the invitation.
